# Generated by Django 2.0.5 on 2018-05-23 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0002_user_account_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_account',
            old_name='user',
            new_name='account_user',
        ),
    ]
