# Generated by Django 2.0.5 on 2018-05-23 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0003_auto_20180523_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=19)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('purchase_date', models.DateTimeField(auto_now=True)),
                ('gain_loss', models.DecimalField(decimal_places=2, max_digits=19)),
                ('account_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_accounts.User_Account')),
            ],
        ),
    ]
