# Generated by Django 2.0.5 on 2018-05-23 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0004_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='account_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='user_accounts.User_Account'),
        ),
    ]
