# Generated by Django 2.0.5 on 2018-05-23 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0005_auto_20180523_2326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='gain_loss',
        ),
    ]
