# Generated by Django 2.0.5 on 2018-05-24 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0007_auto_20180523_2338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_account',
            old_name='balance',
            new_name='cash',
        ),
    ]
