# Generated by Django 2.0.5 on 2018-05-24 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0008_auto_20180524_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='account_user',
            new_name='user_account',
        ),
    ]
