# Generated by Django 2.0.5 on 2018-05-24 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0009_auto_20180524_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
            ],
        ),
        migrations.RemoveField(
            model_name='stock',
            name='user_account',
        ),
        migrations.RemoveField(
            model_name='user_account',
            name='cash',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='user_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='user_accounts.User_Account'),
        ),
        migrations.AddField(
            model_name='stock',
            name='portfolio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_accounts.Portfolio'),
            preserve_default=False,
        ),
    ]
