# Generated by Django 2.0.5 on 2018-05-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0011_auto_20180524_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='purchase_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
