# Generated by Django 2.0.5 on 2018-05-24 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0012_auto_20180524_1949'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stock',
            new_name='User_Stock',
        ),
    ]
