# Generated by Django 2.0.5 on 2018-05-25 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0013_auto_20180524_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_account',
            name='account_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
