# Generated by Django 2.0.5 on 2018-05-25 22:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0014_auto_20180525_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='user_account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='user_accounts.User_Account'),
        ),
        migrations.AlterField(
            model_name='user_account',
            name='account_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to=settings.AUTH_USER_MODEL),
        ),
    ]
