# Generated by Django 2.0.5 on 2018-05-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0016_remove_portfolio_cash'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='cash',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19),
        ),
    ]
