# Generated by Django 2.0.5 on 2018-06-03 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0018_auto_20180601_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_account',
            name='joined',
            field=models.DateTimeField(auto_now_add=True, default='2018-05-28T22:23:02.033292Z'),
            preserve_default=False,
        ),
    ]
