# Generated by Django 2.0.5 on 2018-06-15 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0020_watch_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily_Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=19)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_balance', to='user_accounts.Portfolio')),
            ],
        ),
    ]
