# Generated by Django 2.0.5 on 2018-06-16 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0021_daily_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock_Sell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell_date', models.DateTimeField(auto_now_add=True)),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_history', to='user_accounts.Portfolio')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='user_accounts.User_Stock')),
            ],
        ),
    ]
