# Generated by Django 2.0.5 on 2018-06-17 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0022_stock_sell'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='user_accounts.User_Account')),
            ],
        ),
        migrations.CreateModel(
            name='Stock_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=19)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('sell_date', models.DateTimeField(auto_now_add=True)),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_history', to='user_accounts.History')),
            ],
        ),
        migrations.RemoveField(
            model_name='stock_sell',
            name='portfolio',
        ),
        migrations.RemoveField(
            model_name='stock_sell',
            name='stock',
        ),
        migrations.DeleteModel(
            name='Stock_Sell',
        ),
    ]
