# Generated by Django 2.0.5 on 2018-06-22 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0023_auto_20180617_0028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='user_account',
        ),
        migrations.RemoveField(
            model_name='stock_history',
            name='history',
        ),
        migrations.DeleteModel(
            name='History',
        ),
        migrations.DeleteModel(
            name='Stock_History',
        ),
    ]
