# Generated by Django 2.0.5 on 2018-06-25 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0024_auto_20180622_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intraday_Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('cash_balance', models.DecimalField(decimal_places=2, max_digits=19)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intradat_balance', to='user_accounts.Portfolio')),
                ('snap_stocks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snap_stocks', to='user_accounts.User_Stock')),
            ],
        ),
    ]
