# Generated by Django 2.0.5 on 2018-06-25 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0028_auto_20180625_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_balance',
            name='daily_stocks',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_stocks', to='user_accounts.User_Stock'),
        ),
    ]
