# Generated by Django 2.0.5 on 2018-06-25 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0030_auto_20180625_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intraday_balance',
            old_name='cash_balance',
            new_name='cash',
        ),
        migrations.RemoveField(
            model_name='daily_balance',
            name='daily_stocks',
        ),
        migrations.RemoveField(
            model_name='intraday_balance',
            name='snap_stocks',
        ),
        migrations.AddField(
            model_name='user_stock',
            name='daily_balance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_stocks', to='user_accounts.Daily_Balance'),
        ),
        migrations.AddField(
            model_name='user_stock',
            name='intraday_balance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intraday_stocks', to='user_accounts.Intraday_Balance'),
        ),
    ]
