# Generated by Django 2.0.5 on 2018-06-25 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0031_auto_20180625_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_stock',
            name='daily_balance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_stocks', to='user_accounts.Daily_Balance'),
        ),
    ]
