# Generated by Django 2.0.5 on 2018-06-25 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0033_auto_20180625_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_balance',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
