# Generated by Django 2.0.5 on 2018-06-25 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0034_auto_20180625_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_balance',
            name='date',
            field=models.DateField(),
        ),
    ]
