# Generated by Django 2.0.5 on 2018-06-25 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0035_auto_20180625_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance_Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=19)),
            ],
        ),
        migrations.RemoveField(
            model_name='daily_balance',
            name='stock_symbols',
        ),
        migrations.AddField(
            model_name='balance_stock',
            name='daily_balance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_stocks', to='user_accounts.Daily_Balance'),
        ),
    ]
