# Generated by Django 2.0.5 on 2018-06-26 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0036_auto_20180625_2323'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='daily_balance',
            order_with_respect_to='date',
        ),
    ]
