# Generated by Django 2.0.5 on 2018-06-26 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0037_auto_20180626_1545'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='daily_balance',
            options={'ordering': ['date']},
        ),
        migrations.AlterOrderWithRespectTo(
            name='daily_balance',
            order_with_respect_to=None,
        ),
    ]
