# Generated by Django 2.0.5 on 2018-06-26 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0038_auto_20180626_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance_stock',
            name='daily_balance',
        ),
        migrations.RenameField(
            model_name='daily_balance',
            old_name='cash',
            new_name='balance',
        ),
        migrations.DeleteModel(
            name='Balance_Stock',
        ),
    ]
