# Generated by Django 2.0.5 on 2018-07-09 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0039_auto_20180626_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intraday_balance',
            name='portfolio',
        ),
        migrations.DeleteModel(
            name='Intraday_Balance',
        ),
    ]
